name: "awards_dbt"
version: "1.0.0"
config-version: 2

profile: "awards_dbt"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  awards_dbt:
    +materialized: view
    staging:
      +materialized: view