"""create transaction tables

Revision ID: 66d9c8b97b18
Revises: 
Create Date: 2023-08-26 11:26:07.105824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d9c8b97b18'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistance_transactions',
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.Column('awarding_agency_code', sa.String(), nullable=True),
    sa.Column('awarding_agency_name', sa.String(), nullable=True),
    sa.Column('federal_action_obligation', sa.Float(), nullable=True),
    sa.Column('primary_place_of_performance_state_name', sa.String(), nullable=True),
    sa.Column('recipient_name', sa.String(), nullable=True),
    sa.Column('recipient_uei', sa.String(), nullable=True),
    sa.Column('usaspending_permalink', sa.String(), nullable=True),
    sa.Column('assistance_award_unique_key', sa.String(), nullable=False),
    sa.Column('assistance_transaction_unique_key', sa.String(), nullable=False),
    sa.Column('assistance_type_code', sa.String(length=2), nullable=True),
    sa.Column('cfda_number', sa.String(length=6), nullable=True),
    sa.Column('cfda_title', sa.String(), nullable=True),
    sa.Column('original_loan_subsidy_cost', sa.Float(), nullable=True),
    sa.Column('generated_pragmatic_obligations', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('assistance_transaction_unique_key')
    )
    op.create_table('procurement_transactions',
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.Column('awarding_agency_code', sa.String(), nullable=True),
    sa.Column('awarding_agency_name', sa.String(), nullable=True),
    sa.Column('federal_action_obligation', sa.Float(), nullable=True),
    sa.Column('primary_place_of_performance_state_name', sa.String(), nullable=True),
    sa.Column('recipient_name', sa.String(), nullable=True),
    sa.Column('recipient_uei', sa.String(), nullable=True),
    sa.Column('usaspending_permalink', sa.String(), nullable=True),
    sa.Column('contract_award_unique_key', sa.String(), nullable=False),
    sa.Column('contract_transaction_unique_key', sa.String(), nullable=False),
    sa.Column('naics_code', sa.String(), nullable=True),
    sa.Column('naics_description', sa.String(), nullable=True),
    sa.Column('product_or_service_code', sa.String(), nullable=True),
    sa.Column('product_or_service_code_description', sa.String(), nullable=True),
    sa.Column('generated_pragmatic_obligations', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('contract_transaction_unique_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procurement_transactions')
    op.drop_table('assistance_transactions')
    # ### end Alembic commands ###
