"""add ppop county fips

Revision ID: dfce17e120c7
Revises: 8bb6c0e38faa
Create Date: 2023-10-24 09:26:09.218599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfce17e120c7'
down_revision: Union[str, None] = '8bb6c0e38faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistance_transactions', sa.Column('prime_award_transaction_place_of_performance_county_fips_code', sa.String(length=6), nullable=True))
    op.add_column('procurement_transactions', sa.Column('prime_award_transaction_place_of_performance_county_fips_code', sa.String(length=6), nullable=True))
    op.add_column('transactions', sa.Column('prime_award_transaction_place_of_performance_county_fips_code', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'prime_award_transaction_place_of_performance_county_fips_code')
    op.drop_column('procurement_transactions', 'prime_award_transaction_place_of_performance_county_fips_code')
    op.drop_column('assistance_transactions', 'prime_award_transaction_place_of_performance_county_fips_code')
    # ### end Alembic commands ###
